server:  
  port: 8888
spring:  
  application:
    name: servicio-config-server  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hearias6/cursoMicroservicioConfig

logging:  
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.curso.microservicios: 'DEBUG'  